"""
HAMCPTools — compatibility MCP surface for Home Assistant (`ha_*` tool names).

Exposes the same 81 tool names; execution is delegated to
`hamcp_tools_impl.dispatch_hamcp_full` (HA REST, WebSocket, Supervisor,
/config filesystem, git checkpoint, HACS helpers).
"""
from __future__ import annotations

from app.hamcp_tools_impl import dispatch_hamcp_full

dispatch_hamcp_tool = dispatch_hamcp_full

HAMCP_TOOL_NAMES: list[str] = [
    "ha_check_theme_config",
    "ha_reload_themes",
    "ha_delete_theme",
    "ha_update_theme",
    "ha_create_theme",
    "ha_get_theme",
    "ha_list_themes",
    "ha_call_service",
    "ha_add_repository",
    "ha_list_repositories",
    "ha_set_addon_options",
    "ha_get_addon_options",
    "ha_update_addon",
    "ha_restart_addon",
    "ha_stop_addon",
    "ha_start_addon",
    "ha_uninstall_addon",
    "ha_install_addon",
    "ha_addon_logs",
    "ha_addon_info",
    "ha_list_installed_addons",
    "ha_list_addons",
    "ha_list_store_addons",
    "ha_hacs_repository_details",
    "ha_hacs_update_all",
    "ha_hacs_search",
    "ha_hacs_install_repository",
    "ha_hacs_list_repositories",
    "ha_hacs_status",
    "ha_uninstall_hacs",
    "ha_install_hacs",
    "ha_logbook_entries",
    "ha_git_diff",
    "ha_end_checkpoint",
    "ha_create_checkpoint",
    "ha_git_rollback",
    "ha_git_history",
    "ha_git_pending",
    "ha_git_commit",
    "ha_delete_script",
    "ha_update_script",
    "ha_list_scripts",
    "ha_get_script",
    "ha_create_script",
    "ha_delete_automation",
    "ha_update_automation",
    "ha_list_automations",
    "ha_get_automation",
    "ha_create_automation",
    "ha_delete_helper",
    "ha_create_helper",
    "ha_list_helpers",
    "ha_remove_device_registry_entry",
    "ha_update_device_registry",
    "ha_get_device_registry_entry",
    "ha_get_device_registry",
    "ha_delete_area",
    "ha_update_area",
    "ha_create_area",
    "ha_get_area_registry_entry",
    "ha_get_area_registry",
    "ha_find_dead_entities",
    "ha_remove_entity_registry_entry",
    "ha_update_entity_registry",
    "ha_get_entity_registry_entry",
    "ha_get_entity_registry",
    "ha_rename_entity",
    "ha_get_entity_state",
    "ha_list_entities",
    "ha_delete_dashboard",
    "ha_apply_dashboard",
    "ha_preview_dashboard",
    "ha_analyze_entities_for_dashboard",
    "ha_get_logs",
    "ha_restart",
    "ha_reload_config",
    "ha_check_config",
    "ha_delete_file",
    "ha_list_files",
    "ha_write_file",
    "ha_read_file",
]
